# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/payload.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protobuf/payload.proto\"\xd2\x01\n\x0b\x44\x61ppPayload\x12#\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x13.DappPayload.Action\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12&\n\x0b\x63reate_user\x18\x03 \x01(\x0b\x32\x11.CreateUserAction\x12&\n\x0bupdate_user\x18\x04 \x01(\x0b\x32\x11.UpdateUserAction\";\n\x06\x41\x63tion\x12\x0f\n\x0b\x43REATE_DATA\x10\x00\x12\x0f\n\x0b\x43REATE_USER\x10\x01\x12\x0f\n\x0bUPDATE_USER\x10\x02\"a\n\x10\x43reateUserAction\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\"a\n\x10UpdateUserAction\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\tb\x06proto3')
)



_DAPPPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='DappPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_DATA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_USER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_USER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=178,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_DAPPPAYLOAD_ACTION)


_DAPPPAYLOAD = _descriptor.Descriptor(
  name='DappPayload',
  full_name='DappPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='DappPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DappPayload.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_user', full_name='DappPayload.create_user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_user', full_name='DappPayload.update_user', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DAPPPAYLOAD_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=237,
)


_CREATEUSERACTION = _descriptor.Descriptor(
  name='CreateUserAction',
  full_name='CreateUserAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreateUserAction.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='CreateUserAction.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='CreateUserAction.full_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='CreateUserAction.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='CreateUserAction.phone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=336,
)


_UPDATEUSERACTION = _descriptor.Descriptor(
  name='UpdateUserAction',
  full_name='UpdateUserAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateUserAction.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='UpdateUserAction.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='UpdateUserAction.full_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='UpdateUserAction.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='UpdateUserAction.phone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=435,
)

_DAPPPAYLOAD.fields_by_name['action'].enum_type = _DAPPPAYLOAD_ACTION
_DAPPPAYLOAD.fields_by_name['create_user'].message_type = _CREATEUSERACTION
_DAPPPAYLOAD.fields_by_name['update_user'].message_type = _UPDATEUSERACTION
_DAPPPAYLOAD_ACTION.containing_type = _DAPPPAYLOAD
DESCRIPTOR.message_types_by_name['DappPayload'] = _DAPPPAYLOAD
DESCRIPTOR.message_types_by_name['CreateUserAction'] = _CREATEUSERACTION
DESCRIPTOR.message_types_by_name['UpdateUserAction'] = _UPDATEUSERACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DappPayload = _reflection.GeneratedProtocolMessageType('DappPayload', (_message.Message,), {
  'DESCRIPTOR' : _DAPPPAYLOAD,
  '__module__' : 'protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:DappPayload)
  })
_sym_db.RegisterMessage(DappPayload)

CreateUserAction = _reflection.GeneratedProtocolMessageType('CreateUserAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERACTION,
  '__module__' : 'protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserAction)
  })
_sym_db.RegisterMessage(CreateUserAction)

UpdateUserAction = _reflection.GeneratedProtocolMessageType('UpdateUserAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERACTION,
  '__module__' : 'protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserAction)
  })
_sym_db.RegisterMessage(UpdateUserAction)


# @@protoc_insertion_point(module_scope)
